### ISSUE TITLE
Airbyte sync fails when using Replica

### ISSUE THREAD

**Issue by majgaard** [planetscale/airbyte-source#79]
Thank you to your team for #76! I'm very excited that this is now an option.
Unfortunately, syncs have been failing consistently with the following error since upgrading the Airbyte source to the latest version and moving to Replica traffic. I have also attempted a hard reset of my connection (to reset the state) -- but it has not solved the issue.

Is anyone else seeing this as well?

```
2023-10-11 14:18:48 source > PlanetScale Source :: [mydatabase:replica:MyTable shard : -] Continuing with cursor after server timeout
2023-10-11 14:18:48 source > PlanetScale Source :: [mydatabase:replica:MyTable shard : -] peeking to see if there's any new rows
2023-10-11 14:19:33 source > Unable to get latest cursor position: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023-10-11 14:19:33 INFO i.a.w.g.BufferedReplicationWorker(readFromSource):342 - readFromSource: source exception
io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 1
        at io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:339) ~[io.airbyte-airbyte-commons-worker-0.50.24.jar:?]
        at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:232) ~[io.airbyte-airbyte-commons-worker-0.50.24.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by majgaard** [comment]
Thank you 🙏  I knew y'all would have things under control already. Great stuff.

**Comment by Phanatic** [comment]
@majgaard should be fixed in https://github.com/planetscale/airbyte-source/releases/tag/v1.20.0 now
The existing docker image tag at `planetscale/airbyte-source:latest` is also updated if you want to try again.
