### ISSUE TITLE
Docker arm build

### ISSUE THREAD

**Issue by marchellodev** [planetscale/airbyte-source#88]
When adding a planetscale source to the airbyte running on a Hetzner ARM machine, I get the following error:

<img width="524" alt="image" src="https://github.com/planetscale/airbyte-source/assets/61112084/7c3ce875-23e4-410f-845b-ab3a673b4fbc">

On an M1 everything works correctly, probably due to the Rosetta Layer

**Comment by marchellodev** [comment]
Here's the log with the error:

```
airbyte-worker                    | 2023-11-07 07:38:39 ERROR i.a.c.i.LineGobbler(voidCall):149 - WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
airbyte-worker                    | 2023-11-07 07:38:39 ERROR i.a.c.i.LineGobbler(voidCall):149 - [FATAL tini (8)] exec /usr/local/bin/connect failed: Exec format error
airbyte-worker                    | 2023-11-07 07:38:39 INFO i.a.w.i.VersionedAirbyteStreamFactory(detectAndInitialiseMigrators):207 - Unable to detect Protocol Version, assuming protocol version 0.2.0
airbyte-worker                    | 2023-11-07 07:38:39 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):186 - Reading messages from protocol version 0.2.0
airbyte-worker                    | 2023-11-07 07:38:39 WARN i.a.w.g.DefaultGetSpecWorker(run):72 - Spec job subprocess finished with exit code 1
airbyte-worker                    | 2023-11-07 07:38:39 INFO i.a.c.t.TemporalUtils(withBackgroundHeartbeat):321 - Stopping temporal heartbeating...
airbyte-worker                    | 2023-11-07 07:38:39 INFO i.a.c.t.TemporalUtils(withBackgroundHeartbeat):330 - Temporal heartbeating stopped.
airbyte-worker                    | 2023-11-07 07:38:39 WARN i.t.i.a.ActivityTaskExecutors$BaseActivityTaskExecutor(execute):114 - Activity failure. ActivityId=f40f8e9b-42f5-3c2b-b011-13ddd0bea71d, activityType=Run, attempt=1
airbyte-worker                    | java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Error while getting spec from image planetscale/airbyte-source:latest
airbyte-worker                    |     at io.airbyte.commons.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:319) ~[io.airbyte-airbyte-commons-temporal-0.50.33.jar:?]
airbyte-worker                    |     at io.airbyte.workers.temporal.spec.SpecActivityImpl.run(SpecActivityImpl.java:111) ~[io.airbyte-airbyte-workers-0.50.33.jar:?]
airbyte-worker                    |     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
```
